name: 🛠️ Task
description: For work items, to-dos, or specific tasks to complete.
title: "[Task] <Short description of the task>"
labels: [task]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🛠️ Task Description

  - type: textarea
    id: task-summary
    attributes:
      label: Task Summary
      description: What needs to be done? Provide a clear and concise description of the task.
      placeholder: "Write the task details here..."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define what success looks like for this task.
      placeholder: |
        - [ ] Clear goal defined
        - [ ] Reviewed and approved by team
    validations:
      required: false

  - type: input
    id: due-date
    attributes:
      label: Due Date
      description: Optional due date for this task.
      placeholder: "YYYY-MM-DD"
    validations:
      required: false

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any other relevant information or links.
      placeholder: "Links, references, or extra context..."
    validations:
      required: false
